<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon_share_project_1</name>
   <tag></tag>
   <elementGuidId>8357642c-b7ca-4f89-9679-34dc713ae70c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.lean-share-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='732']/div[10]/div[2]/div/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lean-share-2</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reorder-projects-container&quot;)/div[@id=&quot;732&quot;]/div[@class=&quot;table-small projects-last-cell&quot;]/div[@class=&quot;table-cell&quot;]/div[@class=&quot;wrap-action-icon&quot;]/a[@class=&quot;btn btn-xs withTooltip&quot;]/i[@class=&quot;lean-share-2&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='732']/div[10]/div[2]/div/a/i</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a/i</value>
   </webElementXpaths>
</WebElementEntity>
