<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>toggle_reset_yellow</name>
   <tag></tag>
   <elementGuidId>43a10567-7666-4825-8d0d-5de7c432a2ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.text-white.lean-alert-circle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='results']/div/div/div/button[2]/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-white lean-alert-circle</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;results&quot;)/div[@class=&quot;theader&quot;]/div[@class=&quot;table-header text-left&quot;]/div[@class=&quot;project-order-container&quot;]/button[@class=&quot;btn btn-reorder-rows reorder-reset&quot;]/i[@class=&quot;text-white lean-alert-circle&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='results']/div/div/div/button[2]/i</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/button[2]/i</value>
   </webElementXpaths>
</WebElementEntity>
